# Generated by Django 4.0 on 2021-12-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Models',
            new_name='Tweet',
        ),
    ]
